# Generated by Django 6.0 on 2025-12-14 17:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('bio', models.TextField(blank=True, null=True)),
                ('birth_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2025)])),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=120)),
                ('isbn', models.CharField(db_index=True, max_length=20, unique=True)),
                ('publication_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2025)])),
                ('genre', models.CharField(choices=[('FICTION', 'Fiction'), ('NON_FICTION', 'Non Fiction'), ('SCIENCE', 'Science'), ('TECHNOLOGY', 'Technology'), ('HISTORY', 'History'), ('BIOGRAPHY', 'Biography'), ('PHILOSOPHY', 'Philosophy'), ('PSYCHOLOGY', 'Psychology'), ('SELF_HELP', 'Self Help'), ('BUSINESS', 'Business'), ('ECONOMICS', 'Economics'), ('EDUCATION', 'Education'), ('POLITICS', 'Politics'), ('RELIGION', 'Religion'), ('ART', 'Art'), ('DESIGN', 'Design'), ('MUSIC', 'Music'), ('POETRY', 'Poetry'), ('DRAMA', 'Drama'), ('ROMANCE', 'Romance'), ('MYSTERY', 'Mystery'), ('THRILLER', 'Thriller'), ('HORROR', 'Horror'), ('FANTASY', 'Fantasy'), ('SCIENCE_FICTION', 'Science Fiction'), ('ADVENTURE', 'Adventure'), ('CHILDREN', 'Children'), ('YOUNG_ADULT', 'Young Adult'), ('COMICS', 'Comics'), ('GRAPHIC_NOVEL', 'Graphic Novel'), ('LANGUAGE', 'Language'), ('TRAVEL', 'Travel'), ('HEALTH', 'Health'), ('MEDICINE', 'Medicine'), ('COOKING', 'Cooking'), ('SPORTS', 'Sports')], max_length=20)),
                ('total_copies', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('available_copies', models.PositiveIntegerField(editable=False)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.author')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField(blank=True)),
                ('membership_type', models.CharField(choices=[('REGULAR', 'Regular'), ('PREMIUM', 'Premium'), ('STAFF', 'Staff')], max_length=10)),
                ('is_active_member', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BorrowingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(blank=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('is_returned', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrowings', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowings', to='books.userprofile')),
            ],
        ),
    ]
