# Generated by Django 6.0 on 2025-12-16 07:35

import books.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birth_year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000), books.models.validate_year_not_in_future]),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000), books.models.validate_year_not_in_future]),
        ),
        migrations.AlterField(
            model_name='borrowingrecord',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
