# Generated by Django 6.0 on 2025-12-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_author_birth_year_alter_book_publication_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='membership_type',
            field=models.CharField(choices=[('REGULAR', 'regular'), ('PREMIUM', 'premium'), ('STAFF', 'staff')], max_length=10),
        ),
    ]
